### ISSUE TITLE
validateJwt() error

### ISSUE THREAD

**Issue by Sakaiiz** [timonson/djwt#12]
Hello !
The `validateJwt()` function changed since your last commit and now I can't have my token when using it.
The token I get is "_Invalid Signature_" : `eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJhZG1pbiIsImV4cCI6MTU5MTgyMDU5NzQ1NX0.QcfGBvexnUUP0b1-5KlEM7A3AuMtsTjijFVOhaYNRBE`
When I try your exemple form your github in my project It doesn't work

Maybe I do something wrong but I don't know how to solve this 
Thanks for your work and help !

**Comment by timonson** [comment]
Hi @Sakaiiz I just tested the examples in this repo again and they do work. What I would recommend is using `deno run -A --reload file.ts` once. Please let me know if this fixes it.
