### ISSUE TITLE
JWT is expired 

### ISSUE THREAD

**Issue by vupham-zingbox** [timonson/djwt#17]
When I verify a token that was created by jsonwebtoken node package, it always say that token is expired, althought it's not.

**Comment by timonson** [comment]
Hi @vupham-zingbox I assume you are using the latest djwt version? If you do, could you please try out if this version of djwt works: https://deno.land/x/djwt@9eae2530bb02574023198245b0af291d77667d0a/validate.ts

**Comment by timonson** [comment]
Oh and please post the jwt if possible.

**Comment by vupham-zingbox** [comment]
I resolved the problem by giving the exp the milliseconds. By default the expiresIn of jsonwebtoken generate seconds.
