### ISSUE TITLE
Consistency

### ISSUE THREAD

**Issue by gungunfebrianza** [timonson/djwt#18]
Last time we need 3 parameters and then now changed to 1 parameter, honnestly its really annoying.

![image](https://user-images.githubusercontent.com/5908094/87921555-eeea4800-caa4-11ea-97be-f4ee8d4f7c28.png)

**Comment by timonson** [comment]
Sorry about that @gungunfebrianza . I am very confident that this was the last time the API was changed with breaking changes.
