### ISSUE TITLE
The requested module does not provide export

### ISSUE THREAD

**Issue by pmprosociety** [timonson/djwt#20]
Getting an odd bug in my environment - would you have any advice on troubleshooting?

in my /deps.js - I have the line:
`export { makeJwt, setExpiration, Jose, Payload } from "https://deno.land/x/djwt/create.ts"`
To support subsequent imports into other project files as needed. 

When deno run -A -r ./bin/server.js

The following error occurs:

`error: Uncaught SyntaxError: The requested module 'https://deno.land/x/djwt/create.ts' does not provide an export named 'Jose'`

Same is true for "Payload"

`error: Uncaught SyntaxError: The requested module 'https://deno.land/x/djwt/create.ts' does not provide an export named 'Payload'`

Both "makeJWT" and "setExpiration" seem not to cause error...

Version:
deno 1.2.1
v8 8.5.216
typescript 3.9.2

**Comment by timonson** [comment]
Hi @pmprosociety , it works for me. I have the following code in a `mod.ts` file:

```typescript
export { validateJwt } from "../validate.ts";
export {
  makeJwt,
  setExpiration,
  Jose,
  Payload,
} from "https://deno.land/x/djwt/create.ts";
```

Would you mind posting the whole file? By the way I have `tsc` version 3.9.2, but I don't think that this causes the issue.

Are you sure you are importing the correct file paths in the other file?

**Comment by pmprosociety** [comment]
Thanks for your advice - I must be configuring things incorrectly, please let me know if you find any errors. 

Posted the whole files here: https://github.com/pmprosociety/deno-template
https://github.com/pmprosociety/deno-template/blob/master/deps.js

Reproduced error:
![recording](https://user-images.githubusercontent.com/16341958/88936393-db7f6f80-d250-11ea-8ae2-0a05c1818185.gif)

**Comment by timonson** [comment]
No problem @pmprosociety . You cannot import/export  `.ts` files inside of `.js` files. When you convert your javascript files to typescript files it will work. Please let me know if you could fix it the way I described.

**Comment by pmprosociety** [comment]
Works now, thank you.

**Comment by pmprosociety** [comment]
@timonson Is there any way around this if you don't want to change the whole project to .ts?

**Comment by timonson** [comment]
@pmprosociety you could bundle the library to javascript.

Download [this file](https://github.com/timonson/shadowBase/blob/master/bundler.ts) and `run deno run --unstable -A bundler.ts validate.ts` for example to convert the `validate.ts` file to javascript.
