### ISSUE TITLE
Erro 404 - Update version encoding 

### ISSUE THREAD

**Issue by eniwez** [timonson/djwt#22]
in validate.ts file, I have error in line 3, because link version is wrong

Error
```ts
import { encodeToString as convertUint8ArrayToHex } from "https://deno.land/std@v0.63.0/encoding/hex.ts";
```

Solution
```ts
import { encodeToString as convertUint8ArrayToHex } from "https://deno.land/std@0.63.0/encoding/hex.ts";
```

**Comment by timonson** [comment]
Hi @eniwez , unfortunately I can't replicate this error. Is it possible that this was a temporary mistake on the deno server side?

**Comment by timonson** [comment]
Nevertheless your solution is the *more correct* one it seems. Thank you!
