### ISSUE TITLE
Advice on setExpiration() for exp claim

### ISSUE THREAD

**Issue by PaulFish-Radius** [timonson/djwt#24]
Could you provide examples on how to set the jwt 'exp' claim with setExpiration():

1) a date four months from the current date
2) a date 16 hours from the current date

Thank you

**Comment by timonson** [comment]
Are the examples in the README not sufficient @PaulFish-Radius ?

**Comment by PaulFish-Radius** [comment]
working now ty - just having a hard time with javascript's Date/Time API's.

**Comment by timonson** [comment]
Glad it works now @PaulFish-Radius ! I share your feelings about the JavaScript Date API :)
