### ISSUE TITLE
Advice | Accessing a JWT Claim

### ISSUE THREAD

**Issue by PaulFish-Radius** [timonson/djwt#25]
Noob here - what's the best way to access claims on a JWT once validation has passed? 

![image](https://user-images.githubusercontent.com/58608363/89724605-51af6f00-d9d3-11ea-97cf-3ba01ffa6768.png)

**Comment by timonson** [comment]
Change line 60 to `console.log(email)`. What is the output?

**Comment by PaulFish-Radius** [comment]
Here we are - any advice on how to think about this error?
![image](https://user-images.githubusercontent.com/58608363/89735408-5ce4b800-da30-11ea-8b4b-98ee7a0efad3.png)

**Comment by timonson** [comment]
```typescript
function isObject(obj: unknown): obj is object {
  return (
    obj !== null && typeof obj === "object" && Array.isArray(obj) === false
  );
}

function has<K extends string>(
  key: K,
  x: object
): x is { [key in K]: unknown } {
  return key in x;
}

if(isObject(jwtpayload) && has("email", jwtpayload)) console.log(jwtpaload.email)
```

Does this work?

**Comment by PaulFish-Radius** [comment]
@timonson that works perfectly! Thank you for being so helpful. 

Could the djwt library be improved to help others who might run into this use case? 
This developer experience for pulling claims from JWT is just OK - (coming from my limited experience in javascript development).

Is the approach you suggested here normal? Just curious to hear your thoughts on this. 

Thank you again.

**Comment by timonson** [comment]
@PaulFish-Radius the issue is that the payload of a JWS might be any value because the specification [says](https://www.rfc-editor.org/rfc/rfc7515.html#page-8):

> The payload can be any content and need not be a representation of a JSON object

Therefore checking if properties actually exist seems to be the right way. But I am open for better solutions of course.

**Comment by PaulFish-Radius** [comment]
@timonson thank you for the addition - its great! 
A best practice/ code example the readme for showing how to use `isObject`, `hasProperty`, `isExpired` would go a long way in helping others - I'm sure this will increase the popularity of the library as I'm sure its a common use case.

**Comment by timonson** [comment]
I added some information to the README.md https://github.com/timonson/djwt/commit/eaeecdc33f52d4ecae666d9e26ccfa51c9d04a21 .

**Comment by timonson** [comment]
Just for your information: My suggestions in this issue are deprecated now. The function `verify` returns a `Payload` object and is **not** an `unknown` value anymore. Thanks
