### ISSUE TITLE
Question: Would you mind if I publish this additionally on nest.land for optimal persistence?

### ISSUE THREAD

**Issue by michael-spengler** [timonson/djwt#27]
https://nest.land/

Or would you rather do it yourself?

**Comment by timonson** [comment]
@michael-spengler this is a great idea. I just published djwt on https://nest.land/package/djwt. I am not very familar with this service yet, so please let me know if I did something wrong. Thank you!  
https://github.com/timonson/djwt/commit/eaeecdc33f52d4ecae666d9e26ccfa51c9d04a21

**Comment by michael-spengler** [comment]
cool @timonson - you could add an entry in the egg.json saying:

repository: "https://github.com/timonson/djwt"

this would help people to give feedback / improvement proposals over time.

**Comment by timonson** [comment]
Should I use the same versions like on Github @michael-spengler  ?

**Comment by michael-spengler** [comment]
This is also a really good question - I do not provide versions in the egg.json typically - rather going with 
`eggs publish --bump minor ` as an example.

I created a related issue yesterday. A solution of this issue could perhaps automatically take the release / version which is also used for deno.land: https://github.com/denoland/deno_registry2/issues/128 

Feel free to give it a thumbs up if you like it.

**Comment by michael-spengler** [comment]
in case you're not already in the following links might be valuable for you:
Deno: https://discord.gg/HyeKmx
Arweave: https://discord.gg/xJhCUf
