### ISSUE TITLE
JWT invalid?

### ISSUE THREAD

**Issue by richcorbs** [timonson/djwt#3]
I can generate a JWT just fine but when I try to validate the JWT it is invalid somehow:

```
const jwt = await makeJwt({ header, payload, jwtSecretKey })
const isJwtValid = await validateJwt(jwt, jwtSecretKey, { isThrowing: false })
```

In this case `isJwtValid === null`.

Also jwt.io indicates that the signature is not valid when I put the secret and JWT in on their landing page.

**Comment by timonson** [comment]
Hi @richcorbs , would you be so kind to give me the exact input data?

**Comment by richcorbs** [comment]
```
const jwtSecretKey = 'my-secret-secret'
const header = { alg: "HS256", typ: "JWT" }
const payload = { iss: "richard", exp: (await setExpiration(new Date().getTime() + 60000)) }
```

**Comment by timonson** [comment]
@richcorbs I could not replicate this error but I have some ideas what might have caused it in your case.

1. Execute the file with `deno run --reload file.ts`.
2. Don't forget that the function `setExpiration` (which doesn't return a promise by the way) never returns the same result twice if you use it the way you did.

I checked the following code with jwt.io and I got the same results:

```typescript
 const key = "my-secret-secret"
const header = { alg: "HS256" as const, typ: "JWT" }
const payload = {
  iss: "richard",
  exp: 1690616799118,
}

const jwt = await makeJwt({ header, payload, key })
const isJwtValid = await validateJwt(jwt, key, { isThrowing: false })
console.log(jwt)
console.log(isJwtValid)
```

![jwt comparison](https://u.teknik.io/eYuxw.png)
