### ISSUE TITLE
1.3 doesn't seem to be available on deno.land

### ISSUE THREAD

**Issue by esquevin** [timonson/djwt#31]
https://deno.land/x/djwt@v1.3 is returning a 404 at the moment

https://deno.land/x/djwt@v1.2 is the last one available.

>deno.land/x downloads and stores your repository contents every time you create a git tag. We only do this once for every tag. This ensures that the contents we serve for a specific version can never change.
Our service needs to get informed whenever a new tag is created. For this purpose we use GitHub webhooks.

Maybe there is an issue with the webhook configuration ? Or is it something on their side ?

**Comment by timonson** [comment]
My best guess right now is that it takes a while for updating. If it doesn't work in a couple of hours I will ask on discord about it. Thank you for letting me know @esquevin !

**Comment by timonson** [comment]
It is the webhook @esquevin . I will fix it in a couple of hours.

**Comment by PaulFish-Radius** [comment]
thanks @timonson for the great library and this fix.

**Comment by timonson** [comment]
Unfortunately v1.3 is *a lost cause*. But Webhooks are integrated now and v1.4 works.
