### ISSUE TITLE
Feature Request: ES256

### ISSUE THREAD

**Issue by nathanqueija** [timonson/djwt#33]
Hello there,

First of all thanks for the great work on this library. I'm finding it very useful.
I'm using it to sign in with Apple and it requires that the algorithm is `ES256`.
Do you have any plans to add this to the library?

Thanks

**Comment by timonson** [comment]
Hi @nathanqueija ,

I would like to implement the ES256 algorithm as well, but unfortunately I have not seen a library for deno which generates this encryption. 

The good news is that there has been a lot of progress in the deno *environment* lately, so I guess it is just a matter of time.

I hope this answers your question.

**Comment by nathanqueija** [comment]
Thanks for the response @timonson .
Yeah, it makes sense. I don't know any libraries that can generate this encryption.
I'll keep looking for it and will let you know if I find something.
