### ISSUE TITLE
Error using @v1.9 with deno 1.5.0

### ISSUE THREAD

**Issue by Robspin** [timonson/djwt#37]
warning: Compiled module not found "https://deno.land/std@0.75.0/encoding/base64url.ts"
  From: https://deno.land/x/djwt@v1.9/_depts.ts
    If the source module contains only types, use `import type` and `export type` to import it instead.

warning: Compiled module not found "https://deno.land/std@0.75.0/encoding/hex.ts"
  From: https://deno.land/x/djwt@v1.9/_depts.ts
    If the source module contains only types, use `import type` and `export type` to import it instead.

warning: Compiled module not found "https://deno.land/std@0.75.0/hash/sha256.ts"
  From: https://deno.land/x/djwt@v1.9/_depts.ts
    If the source module contains only types, use `import type` and `export type` to import it instead.

warning: Compiled module not found "https://deno.land/std@0.75.0/hash/sha512.ts"
  From: https://deno.land/x/djwt@v1.9/_depts.ts
    If the source module contains only types, use `import type` and `export type` to import it instead.

warning: Compiled module not found "https://deno.land/x/god_crypto@v1.4.3/rsa.ts"
  From: https://deno.land/x/djwt@v1.9/_depts.ts
    If the source module contains only types, use `import type` and `export type` to import it instead.

error: Uncaught SyntaxError: The requested module 'https://deno.land/std@0.75.0/encoding/hex.ts' does not provide an export named 'decodeString' 

Not sure what is causing this, the module does in fact has the export it needs...

**Comment by timonson** [comment]
Did you try the `--reload` flag?

**Comment by Robspin** [comment]
I did now, didnt change, also manually deleted cached imports before.
Here is the repository of my [current code](https://github.com/Robspin/greentemple).

**Comment by Robspin** [comment]
The error went away when I downgraded my deno to 1.4.0, and then upgraded back to 1.5.0... Closed issue
