### ISSUE TITLE
deno bundle doesn't work on mod.ts

### ISSUE THREAD

**Issue by alexanderGalushka** [timonson/djwt#39]
tried deno 1.5.1 all the way down to 1.0.0 - no luck

getting rid of _deps.ts and putting decodeString and encodeToString directly from deno encoding lib for each module _signature.ts and mod.ts make the bundle work fine

**Comment by timonson** [comment]
I don't think this is an issue for this library. I think it would be great if you would open this issue in the deno repo.

**Comment by alexanderGalushka** [comment]
Currently djwt can not be bundled. Libraries bundling is a common and widely used Deno feature. I agree it might not be an issue with the djwt library itself, but an easy work around can be implemented, see the suggested fix above. 

I think bundle doesn't work well with circular dependencies. I will definitely submit an issue with Deno itself.

But just food for thought, is _deps.ts really needed for djwt? If you strongly believe that it does, I'd like to understands what are the benefits so the broken Deno bundle of djwt library can be justified.

**Comment by alexanderGalushka** [comment]
Deno bundle command doesn't error out but the bundled code doesn't contain the implementation for convertUint8ArrayToHex

which is essentially encodeToString function from "https://deno.land/std@0.75.0/encoding/hex.ts"

that's how issue manifests itself:

```
ReferenceError: convertUint8ArrayToHex is not defined
    at file:///Users/agalushka/Documents/repos/test_djwt/djwt.js:2825:17
    at Array.map (<anonymous>)
    at decode4 (file:///Users/agalushka/Documents/repos/test_djwt/djwt.js:2815:62)
    at verify (file:///Users/agalushka/Documents/repos/test_djwt/djwt.js:2856:47)
    at main (file:///Users/agalushka/Documents/repos/test_djwt/main.js:55:41)
```

**Comment by bicarlsen** [comment]
Just started with Deno, so not sure if I can provide much insight, but I am receiving the error:

> An unsupported media type was attempted to be imported as a module.
>   Specifier: https://deno.land/x@v1.9/djwt/mod.ts
>   MediaType: Unknown

when running `import { create } from 'https://deno.land/x@v1.9/djwt/mod.ts';` which seems related to this.

**Comment by timonson** [comment]
What exactly do I have to do to replicate this?

**Comment by alexanderGalushka** [comment]
@timonson I've put together a quick test, follow the readme steps to reproduce https://github.com/alexanderGalushka/djwt_test

**Comment by bicarlsen** [comment]
> What exactly do I have to do in order to replicate this?
For me it occurs any try to import it, even if it is the only thing in the file.

i.e.
**test.ts**
```js
import { create } from 'https://deno.land/x@v1.9/djwt/mod.ts';
```
Then running
```bash
deno run test.ts
```
results in the error
> error: An unsupported media type was attempted to be imported as a module.
> Specifier: https://deno.land/x@v1.9/djwt/mod.ts
> MediaType: Unknown

**Comment by timonson** [comment]
@bicarlsen it seems you are using a wrong url. Try this one: https://deno.land/x/djwt@v1.9/mod.ts

**Comment by bicarlsen** [comment]
Great! That resolved the loading issue. Just a heads up, that URL was copied from the README on the [deno.land page](https://deno.land/x/djwt@v1.9).

**Comment by alexanderGalushka** [comment]
@timonson were you be able to reproduce `deno bundle` issue?

**Comment by timonson** [comment]
Yes, it seems to be a `bundler` bug. I would suggest that we wait a couple of more days and see if this https://github.com/swc-project/swc/pull/1212 will fix it. Are you OK with that?

**Comment by alexanderGalushka** [comment]
totally

**Comment by BayoKwendo** [comment]
warning: Compiled module not found "https://deno.land/x/djwt@v1.9/mod.ts"
  From: file:///home/bayo/Work/themeforest/Insight/controllers/authController.ts
    If the source module contains only types, use `import type` and `export type` to import it instead.
error: Uncaught SyntaxError: The requested module 'https://deno.land/x/djwt@v1.9/mod.ts' does not provide an export named 'create

**Comment by timonson** [comment]
Hi @BayoKwendo , this seems to be a `deno` issue as well. Please take a look at this issue here https://github.com/timonson/djwt/issues/37

**Comment by timonson** [comment]
Hi @alexanderGalushka , I believe this issue has been fixed now or am I wrong?

**Comment by alexanderGalushka** [comment]
I've just upgrade to deno v1.5.4, would like to test it out
```
deno bundle "https://deno.land/x/djwt@v1.9/mod.ts" djwt.js
```
getting the following error:

```
Bundle https://deno.land/x/djwt@v1.9/mod.ts
Check https://deno.land/x/djwt@v1.9/mod.ts
error: No such file or directory (os error 2)
```
@timonson can u please try to bundle command as well to confirm

**Comment by timonson** [comment]
I tried your test out before I asked the question and it worked for me.
The single command `deno bundle "https://deno.land/x/djwt@v1.9/mod.ts" djwt.js` works without error on my linux machine, too. Maybe try the `--reload` option?

**Comment by alexanderGalushka** [comment]
@timonson seems to be working
