### ISSUE TITLE
Push to nest.land

### ISSUE THREAD

**Issue by itohatweb** [timonson/djwt#42]
Would it be possible to push the latest version to nest.land? Or is nest.land not supported anymore?

**Comment by timonson** [comment]
Why do you think it has not been updated?

**Comment by itohatweb** [comment]
Since its versioning stops on 0.1.5 I think it is not updated.

**Comment by timonson** [comment]
Oh I understand the confusion now. I began updating on nestland months later and therefore the version numbers are out of sync. But it should be updated now.

**Comment by itohatweb** [comment]
Ah didn't knew that. So basically 0.1.5 is v2 on nest.land

**Comment by timonson** [comment]
Yes

**Comment by itohatweb** [comment]
Ok, thank for your help. I'll close the issue now.
