### ISSUE TITLE
djwt leads to Uncaught (in promise) Error:Unhandled error event reached main worker

### ISSUE THREAD

**Issue by finlaydotb** [timonson/djwt#48]
I introduced djwt into an application I am building, as soon as I do, I start getting this error:

 
```
error: Uncaught (in worker "") TS2304 [ERROR]: Cannot find name 'window'.
  let binaryString = window.atob(b);
                     ~~~~~~
    at https://deno.land/x/god_crypto@v1.4.9/src/helper.ts:60:22
error: Uncaught (in promise) Error: Unhandled error event reached main worker.
    at Worker.#poll (deno:runtime/js/11_workers.js:269:21)
```

This error starts popping up on just adding the dependencies without even using it.

```
export {create} from "https://deno.land/x/djwt@v2.2/mod.ts";
```

Any ideas on how to debug this? Not sure if it matters, but my application has some logic that already uses workers

PS: Maybe related to this? https://stackoverflow.com/questions/62231656/deno-web-workers-cannot-find-name-window

**Comment by timonson** [comment]
Hi thanks for reporting this issue @finlaydotb ! It looks like you have found the right cause.
