### ISSUE TITLE
Add support for ES256

### ISSUE THREAD

**Issue by christianp86** [timonson/djwt#49]
Hi,

I am currently writing an app in deno that syncs playlists between spotify and apple music.
The Apple Music API requites a JWT signed with ES256

https://developer.apple.com/documentation/applemusicapi/getting_keys_and_creating_tokens

If I had the slightest idea how to implement such an algorithm I would be happy to contribute, but maybe some expert here can add the support for ES256.

Regards
Chris

**Comment by timonson** [comment]
The algorithm ECDSA is still missing but will be implemented in deno version 1.14.0 I was told.

**Comment by timonson** [comment]
Is implemented now :)
