### ISSUE TITLE
missing option?

### ISSUE THREAD

**Issue by hazem-saeed** [timonson/djwt#50]
In an older version, the function 'validateJwt' had an option called "isThrowing", which is now missing in the 'verify' function in the current version.
My question is, is it really missing entirely, or did you move it to another function?

Thanks in advance...

**Comment by timonson** [comment]
Hi @hazem-saeed , there are no options for `verify` anymore. The function throws an error if the jwt is invalid. Maybe the [examples](https://github.com/timonson/djwt/blob/master/examples/hmac_example.ts) - where errors are caught - can be helpful if that's an issue. Do you need this option for a specific use case?

**Comment by hazem-saeed** [comment]
Thanks for the quick reply. No, I don't need it for a specific use case. I only wanted it to catch the error. Your example will suffice.
