### ISSUE TITLE
Update std lib dependencies to current version

### ISSUE THREAD

**Issue by grempe** [timonson/djwt#51]
The deps.ts file has dependencies for older versions of the Deno std lib.

https://github.com/timonson/djwt/blob/master/deps.ts

Current version is `0.95.0`

**Comment by timonson** [comment]
As far as I know there have not been made any substantial changes in the latest `std` versions with regards to the dependencies used by `djwt`. But deno will probably implement the Web Crypto API very soon https://github.com/denoland/deno/pull/9614 .

**Comment by David-Else** [comment]
@timonson https://deno.com/blog/v1.12#support-for-more-web-crypto-functions
