### ISSUE TITLE
verify vs decode use case

### ISSUE THREAD

**Issue by borsemayur2** [timonson/djwt#52]
Please explain which to use when. verify requires `secret` so does that make it more safer in comparison?

P.S.: Please enable `discussions` section to ask questions/queries

**Comment by timonson** [comment]
Hi @borsemayur2 , I would summarize it in the following way:

Use `verify` if you want to check if the JWT is valid. For most people and use cases only `create` and `verify` are necessary.

Use `decode` if you want to convert the JWT to a JavaScript object (maybe to see if the JWT has certain claims/properties). It does not really verify anything. It only checks if the *serialization* of the JWT is valid. 

Does this answer your question?

**Comment by borsemayur2** [comment]
Yes. Thanks. Sorry for the late reply.
