### ISSUE TITLE
error: TS2345 [ERROR]: Argument of type '"jwk"' is not assignable to parameter of type '"raw"'. in DENO v 1.13.0

### ISSUE THREAD

**Issue by koanzen** [timonson/djwt#53]
Getting an Error while creating a Token in DENO v 1.13.0

error: TS2345 [ERROR]: Argument of type '"jwk"' is not assignable to parameter of type '"raw"'.
    "jwk",
    ~~~~~
    at https://deno.land/x/god_crypto@v1.4.9/src/rsa/rsa_wc.ts:55:5

**Comment by timonson** [comment]
With deno's new release yesterday we can use the new Web Crypto API. I will fix it until the end of the week.

**Comment by iugo** [comment]
https://github.com/invisal/god_crypto/issues/39

**Comment by timonson** [comment]
I would appreciate a code review https://github.com/timonson/djwt/pull/54
