### ISSUE TITLE
How to use Cert files

### ISSUE THREAD

**Issue by itohatweb** [timonson/djwt#56]
I noticed djwt now wants a CryptoKey and not cert strings anymore. Since I'm pretty new to crypto I would love to have an example of how to use eg RSA key files.

**Comment by timonson** [comment]
Hi, to generate a `CryptoKey ` or `CryptoKeyPair` you can also use the `importKey` method from the Web Crypto API. You should be able to use your .pem files with this method.

Please take a look at this documentation and let me know if it helped: https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto/importKey

Thanks!

**Comment by itohatweb** [comment]
Looks like pkcs8 is not available in deno 🤔

**Comment by koanzen** [comment]
@TS

Easiest way is to declare a Global var for your key and use it to create and verify your JWT.

Just put this code in your Starting Application

-------------------------------------

declare global {
    var yourkey: any;
    interface Window {
      yourkey: any;
    }
}

window.yourkey = await crypto.subtle.generateKey(
    { name: "HMAC", hash: "SHA-512" },
    true,
    ["sign", "verify"],
)

------------------------------------------------

I think this is not a good practice but it works, hope it will help.

**Comment by itohatweb** [comment]
For my application I need to use RSA and I need the tokens to be valid even after a restart.

**Comment by timonson** [comment]
Hi @itohatweb , pkcs8 has been implemented by the deno authors now. 

I added an example for generating, exporting and importing a key in pkcs8 format  [here](https://github.com/timonson/djwt/blob/master/examples/pkcs8_storing_example.ts).  Does it help?

**Comment by itohatweb** [comment]
Yes thank you.
