### ISSUE TITLE
Feature Request: Support JSON Web Key Sets (JWKS)

### ISSUE THREAD

**Issue by grempe** [timonson/djwt#57]
Supporting the retrieval and use of JWKS public keys would be very helpful. This would allow secure use of public key JWT signatures provided by Auth0, Okta, and other JWKS providers. This would allow client or server side tools to validate JWT's signed by Auth0, Okta, and other identity providers.

https://auth0.com/docs/tokens/json-web-tokens/json-web-key-sets
https://developer.okta.com/code/dotnet/jwt-validation/

Here's a sample of a live JWKS keyset:

https://login.truestamp.com/.well-known/jwks.json

Here is a similar project from Auth0 that pulls in a JWKS set for use in their Node Express lib that might provide inspiration for the API:

https://github.com/auth0/node-jwks-rsa

**Comment by panva** [comment]
@grempe As soon as the appropriate WebCryptoAPIs (SubtleCrypto.importKey) [land in Deno](https://github.com/denoland/deno/issues/11690) you'll be able to do

```ts
import { createRemoteJWKSet } from 'https://deno.land/x/jose@VERSION/jwks/remote.ts'
import { jwtVerify } from 'https://deno.land/x/jose@VERSION/jwt/verify.ts'

const JWKS = createRemoteJWKSet(new URL('https://login.truestamp.com/.well-known/jwks.json'))

function verify(jwt: string) {
  const { payload, protectedHeader } = await jwtVerify(jwt, JWKS, {
    issuer: 'urn:example:issuer',
    audience: 'urn:example:audience'
  })
  return { payload, protectedHeader }
}
```

**Comment by grempe** [comment]
Thanks @panva for the comment and example. I will keep an eye on your JOSE implementation and its Deno support.

**Comment by timonson** [comment]
Thanks @panva ! I would recommend using https://deno.land/x/jose for more complex applications.
