### ISSUE TITLE
mod.ts missing on deno.land

### ISSUE THREAD

**Issue by Lite5h4dow** [timonson/djwt#58]
cant cache `deno.land/x/djwt/mod.ts` as its not there, making the example files invalid.

**Comment by timonson** [comment]
It is not missing. Maybe try the `deno run --reload` flag.

**Comment by Lite5h4dow** [comment]
![image](https://user-images.githubusercontent.com/18059545/130529906-e00aa457-28cb-4834-9971-aae54416c2c3.png)

**Comment by timonson** [comment]
It is probably the cache in your browser. Can you clear it?

**Comment by Lite5h4dow** [comment]
yeah, my bad, for some reason my browser defaulted to 1.2..... i have no idea why tho.
