### ISSUE TITLE
exp/nbf leeway should be configurable

### ISSUE THREAD

**Issue by berlinfox** [timonson/djwt#66]
It's currently hardcoded on 1 second. Would be nice if it's configurable.

https://github.com/timonson/djwt/blob/b154f20ef3827765a09901e0dbef1acf4e026ad9/mod.ts#L111
https://github.com/timonson/djwt/blob/b154f20ef3827765a09901e0dbef1acf4e026ad9/mod.ts#L115

**Comment by timonson** [comment]
Hi @berlinfox , would you mind giving one or two potential use cases where this option might be required please?

**Comment by berlinfox** [comment]
In my use-case I want to send information to a client as fast as possible. Slow network connection could interrupt the refresh interval and invalidate the token in the meantime. Configuring a higher leeway would fix this issue for most of the clients.

**Comment by timonson** [comment]
Thank you for that. Right now, I don't see any problem adding an `options` argument to `verify`. Presumably I will be able to add this option and some other minor changes at the end of this month.

**Comment by timonson** [comment]
What do you think about these changes @berlinfox ? https://github.com/timonson/djwt/pull/69
