### ISSUE TITLE
Moving to JavaScript with JSDoc?

### ISSUE THREAD

**Issue by timonson** [timonson/djwt#68]
By moving to JavaScript including [JSDoc](https://www.typescriptlang.org/docs/handbook/jsdoc-supported-types.html) we could make `djwt` compatible with the browser. By adding `// @ts-check` to the top of the files, it is my understanding that type checks would be executed in importing TypeScript files even if the developer would not have enabled the compiler option `"checkJs"` inside his `deno.json` file.

Am I overlooking any disadvantages or problems here?

Thanks!

**Comment by timonson** [comment]
This won't work in the browser of course as long as we have a typescript dependency with `base64url`.

**Comment by timonson** [comment]
> it is my understanding that type checks would be executed in importing TypeScript files...

This assumption was wrong.

**Comment by lucsoft** [comment]
Don't do this. Stripping types is also very simple and the Deno guys want this stripping types feature also build in into deno.land/x.

I think it's a downgrade (IMO) as JSDocs also makes code less readable
