### ISSUE TITLE
Unexpected change of JWT Key

### ISSUE THREAD

**Issue by so1ve** [timonson/djwt#73]
Hi timonson!
I have created a program that uses djwt and runs on deno deploy. Maybe because Deno Deploy is not running on a single server, the jwt key I created will change from time to time, resulting in unexpected jwt token invalidation. Tokens generated with the old key will be invalid after the key is updated.
```ts
export const jwtKey = await crypto.subtle.generateKey(
   { name: "HMAC", hash: "SHA-512" },
   true,
   ["sign", "verify"],
);
````
Not sure if there is any specific way to solve it.

**Comment by timonson** [comment]
Does it not work if you create a key only once in the whole deployed app?

**Comment by chrisyalamov** [comment]
The Web Crypto API has methods for importing and exporting keys (see the [mdn web docs](https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto/exportKey) for more info)

1. **Generate a key**
  ```js
  const key = await crypto.subtle.generateKey(
    { name: "HMAC", hash: "SHA-512" },
    true,
    ["sign", "verify"],
  );
  ```
2. **Create a JWT**
```js
const jwt = await create({ alg: "HS512", typ: "JWT" }, { foo: "bar" }, key);
```
3. **Export the key**
  E.g. write this to a file which you can read later on— it's up to you how you persist this file, depending on your project.
```js
let exportedKey = await crypto.subtle.exportKey("jwk", key)
```
4. **Reimport the key and confirm everything works**
```js
let reimportedKey = await crypto.subtle.importKey(
  "jwk", 
  exportedKey, 
  { name: "HMAC", hash: "SHA-512" }, true, ["sign", "verify"]);

  // Confirm everything works as expected

  console.log(await verify(jwt, reimportedKey))
  // {foo: 'bar'}
```

**Comment by so1ve** [comment]
> 如果在整个已部署的应用中只创建一次密钥，它是否不起作用？

Yes, I exported it in a file (jwt_key.ts):

```ts
export const jwtKey = await crypto.subtle.generateKey(
   { name: "HMAC", hash: "SHA-512" },
   true,
   ["sign", "verify"],
);
```

**Comment by youwei997** [comment]
兄弟，找到解决办法没

**Comment by so1ve** [comment]
没得

**Comment by so1ve** [comment]
> 兄弟，找到解决办法没

没呢

**Comment by timonson** [comment]
Please talk in English guys!
@so1ve wouldn't you agree that this a deno.com issue and not a djwt issue? Although it might be that I have not fully understood the problem yet.

**Comment by so1ve** [comment]
I'm so sorry...it's actually a deno.com issue. https://github.com/denoland/deploy_feedback/issues/237

**Comment by timonson** [comment]
Oh no problem at all. I was rather curious what the problem was. Thank you!

**Comment by so1ve** [comment]
I think this is caused by Deno Deploy being deployed on the edge server, which causes my program to run from scratch every time (including the part that generates the key).
