### ISSUE TITLE
Cannot verify token/secret which verifies successfully using Node

### ISSUE THREAD

**Issue by mlanza** [timonson/djwt#75]
While I am new to JWT I have run virtually the same code through Node's `jsonwebtoken` library and it works.  I am targeting this library, however, to reduce my bundling dependencies.

Running `decode` against my JWT works fine.  Running `verify`, however, results in a null exception:

```console
error: Uncaught TypeError: Cannot read properties of undefined (reading 'name')
    if (keyAlgorithm.name === algAlgorithm.name) {
                     ^
    at verify (https://deno.land/x/djwt@v2.7/algorithm.ts:46:22)
    at Module.verify (https://deno.land/x/djwt@v2.7/mod.ts:151:7)
    at file:///xxx/xxx/xxx/xxxx/src/cf/jwt.js:15:28
```

Here's what I'm running:
```js
//import jwt from "jsonwebtoken"; //I used Node's experimental-module syntax and it works fine.
import * as jwt from "https://deno.land/x/djwt@v2.7/mod.ts";

const token = "...";
const JWT_SECRET = "...";

const decoded = await jwt.decode(token); //success
console.log("decoded", decoded);  

const verified = await jwt.verify(token, JWT_SECRET); //fail!
console.log("verified", verified); 

```

I am certain my secret and token are fine having confirmed them in Node.  The only difference is Node's methods are synchronous and don't require `await`.

My decoded payload follows, sensitive content elided:

```js
[
  { alg: "HS256", typ: "JWT" },
  {
    aud: "authenticated",
    exp: 1664581993,
    sub: "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
    email: "someone@somewhere.com",
    phone: "",
    app_metadata: { provider: "email", providers: [ "email" ] },
    user_metadata: {},
    role: "authenticated",
    session_id: "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
  },
  Uint8Array(32) [ ...
  ]
]
```

**Comment by mlanza** [comment]
For what it's worth, I just reduced my version to use:

```js
import * as jwt from "https://deno.land/x/djwt@v2.1/mod.ts";

```
and added H256:

```js
const verified = await jwt.verify(token, JWT_SECRET, "HS256");
```

And this works!  But not in 2.7.

**Comment by timonson** [comment]
Hi @mlanza , you need a [CryptoKey](https://developer.mozilla.org/en-US/docs/Web/API/CryptoKey) as key in version `v2.7`. Maybe the examples which you can find [here](https://github.com/timonson/djwt/issues/61) will help you.
